name: Check Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Check formatting with Prettier
        run: bun run format:check
