name: "Test Integration"

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test workflow integration
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false
    uses: ./.github/workflows/integration-test-workflow.yml
    with:
      working-directory: integration-test
      main-branch-name: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
      runs-on: ${{ matrix.runs-on }}
